pipeline { 
    agent any 
    stages {
        stage('Inject Variables') { 
            steps { 
                sh '''
                    ISISROOT=$PWD/isis
                    ISIS3DATA=/usgs/cpkgs/isis3/data
                    ISIS3TESTDATA=/usgs/cpkgs/isis3/testData
                    echo $ISISROOT
                    echo $ISIS3TESTDATA
                    echo $ISIS3DATA
                '''
            }
        }
        stage('Prep') { 
            steps { 
                sh '''
                    pwd
                    ls
                    mkdir -p ./install
                    mkdir -p ./build
                    cd ./build
                '''
            }
        }
        stage('Config') { 
            steps { 
                sh '''
                    cmake -GNinja -DCMAKE_INSTALL_PREFIX=install -Disis3Data=/usgs/cpkgs/isis3/data -Disis3TestData=/usgs/cpkgs/isis3/testData ../isis
                    make
                    make install
                '''
            }
        }
        stage('Build') { 
            steps { 
                sh '''
                    ninja
                    ninja install
                '''
            }
        }
        stage('Test'){
            steps {
              sh '''
                  ctest -R_unit
              '''
            }
        }
    }
}