pipeline { 
    agent {
        docker {
         //   label 'cmake'
            image 'usgsastro/docker_linux_isisdeps'
        }
    }
    stages {
        stage('Inject Variables') { 
            steps { 
                sh "docker volume ls && mkdir -p ./install ./build"
            }
        }
        stage('Config') { 
            steps { 
                sh "cd build && cmake -GNinja -DCMAKE_INSTALL_PREFIX=../install -Disis3Data=/usgs/cpkgs/isis3/data -Disis3TestData=/usgs/cpkgs/isis3/testData ../isis"

            }
        }
        stage('Build') { 
            steps { 
                sh "cd build && ninja && ninja install"
            }
        }
//        stage('Test'){
//            steps {
//                dir('build'){
//                    sh '''
//                        ctest -R _unit
//                    '''
//                }
//            }
//        }
    }
    post {
        success {
            sh 'pwd && ls'
            archiveArtifacts artifacts: "build/objects/*.o"
        }
        always {
            mail to: 'ccombs@usgs.gov',
                    subject: "Build Finished: ${currentBuild.fullDisplayName}",
                    body: "Link: ${env.BUILD_URL}"
//            cleanWs()
        }
    }
}
