Jenkinsfile (Declarative Pipeline)
pipeline { 
    agent any 
    stages {
        stage('Prep') { 
            steps { 
                sh 'pwd'
                sh 'ls'
                sh 'mkdir -p ./install'
                sh 'mkdir -p ./build' 
                sh 'cd ./build'
            }
        }
        stage('Config') { 
            steps { 
                cmake -GNinja -DCMAKE_INSTALL_PREFIX=install -Disis3Data=/usgs/cpkgs/isis3/data -Disis3TestData=/usgs/cpkgs/isis3/testData ../isis
                make
                make install
            }
        }
        stage('Inject Variables') { 
            steps { 
                sh 'ISISROOT="../isis"'
                sh 'ISIS3DATA="/usgs/cpkgs/isis3/data"'
                sh 'ISIS3TESTDATA="/usgs/cpkgs/isis3/testData"'
                sh 'echo $ISISROOT'
                sh 'echo $ISIS3TESTDATA'
                sh 'echo $ISIS3DATA'
            }
        }
        stage('Build') { 
            steps { 
                ninja
                ninja install
            }
        }
        stage('Test'){
            steps {
                ctest -R_unit
            }
        }
    }
}